### ISSUE TITLE
Library NSISpcre.dll left inside temp directory

### ISSUE THREAD

**Issue by DeCiZoR** [mazinsw/NSISpcre#1]
Hello,
After compiling and running the test sample code (NSISpcreTest.nsi), the library NSISpcre.dll (downloaded from http://nsis.sourceforge.net/NSISpcre_plug-in) is left inside temp directory ($PLUGINSDIR).
I have tried your recompiled unicode version (many thanks for it :) ) but it has same bug.

Cannot delete library before the end of code.
Dont want to wait next reboot to force deletion (Delete /REBOOTOK ...).
Is there any way to avoid this ? (method to unload NSISpcre plugin ?)

NSIS version: 3.01

**Comment by mazinsw** [comment]
Can you supply a basic sample to reproduce this problem? I have used macros REMatches and REReplace with no problem, my usage:
```nsis
!insertmacro REMatches
!insertmacro REReplace

${RECaptureMatches} $R3 "^([0-9]+\.[0-9]+)" "$ApacheVersion" 1
Pop $R3

${REReplace} $0 "\\" "$ApacheInstallPath" "/" 1
```

**Comment by DeCiZoR** [comment]
After running program, a folder "nsXXXXX.tmp" ($PLUGINSDIR) is left in current user's temp folder (C:\Users\johndoe\AppData\Local\Temp). Inside it, we find NSISpcre.dll.
I tested many other NSIS plugins and no one except NSISpcre leave DLL in the temp $PLUGINSDIR after closing program.
I tested on Windows 7 Pro French and Windows 10 Pro French. Maybe, i should test with EN-US Windows version.

Sample code to reproduce the problem with your library version or original version (by Robstocks):

```
!include "NSISpcre.nsh"
!insertmacro REMatches
!insertmacro REReplace

Var ApacheVersion
Var ApacheInstallPath

Section "MainSection" SEC01
	StrCpy $ApacheVersion "3.5"
	StrCpy $ApacheInstallPath "C:\program files\apache\"

	${RECaptureMatches} $R3 "^([0-9]+\.[0-9]+)" "$ApacheVersion" 1
	Pop $R3

	${REReplace} $0 "\\" "$ApacheInstallPath" "/" 1
SectionEnd
```

**Comment by xqltt** [comment]
Indeed, There is no nsispcre::unload code. Should you add it?

**Comment by mazinsw** [comment]
@xqltt i don't know if needs some `nsispcre::unload`, maybe some investigating can answer us

**Comment by xqltt** [comment]
This method should be triggered to release NSISpcre when .onGUIEnd is called, otherwise the NSISpcre.dll file will remain in the user's temporary directory
![0](https://user-images.githubusercontent.com/44520521/158302747-c7327594-1336-4949-9014-fa58f3e0f783.png)

**Comment by xqltt** [comment]
I tried using `NSISPcre::REClearAllOptions`
Now it doesn't leave files in the temp directory.
@DeCiZoR

**Comment by DeCiZoR** [comment]
I am late but i want to thank you for your solution.
It works ! :+1:
